### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [27]:
N = int(input('Ввести число: '))
np.arange(N-1, 0-1, -1)

Ввести число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [36]:
N = int(input('Ввести число: '))
data = np.diag(np.arange(N, 0, -1), k=0)
data

Ввести число: 10


array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1]])

In [37]:
for array in data:
    result = np.sum(data)

result

55

### Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [39]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [40]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [41]:
from numpy import linalg

In [44]:
c = linalg.solve(a, b)
c

array([ 0.46666667,  3.84444444, -5.55555556])

In [45]:
np.dot(a, c)

array([ 4., 12., -3.])

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [47]:
# Матрица в виде numpy array
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [48]:
# На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

# Косинусное сходство между векторами
\begin{equation*}
\LARGE
cos(\vec{a}, \vec{b}) = \frac{\vec{a} \dot{} \vec{b}}{|\vec{a}| \space |\vec{b}|}
\end{equation*}

In [50]:
import matplotlib.pyplot as plt

In [51]:
def cosinus(user, next_user_stats):
    """
    Подсчет косинуса угла между векторами user, next_user_stats по их координатам.
    """
    
    # длины векторов
    user_Length = np.linalg.norm(user)
    next_user_stats_Length = np.linalg.norm(next_user_stats)
    
    return np.dot(user, next_user_stats) / (user_Length * next_user_stats_Length)

In [85]:
cos_array = np.array([cosinus(user, next_user_stats) for user in users_stats])
cos_array

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [86]:
most_similar = np.argmax(cos_array)

most_similar

7